http {
     if ($http_user_agent ~* "(Android|iPhone|iPad)") {
      set $app_type "mobile";
      }

      if ($http_user_agent ~* "(Chrome|Firefox|Safari|Edge)") {
          set $app_type "web";
      }

    limit_req_zone $binary_remote_addr zone=one:10m rate=30r/s if=$app_type=mobile;
    limit_req_zone $binary_remote_addr zone=one:10m rate=50r/s if=$app_type=web;

    server {
        listen 80;




        # Веб и мобилки сейчас обращаются на этот ресурс
        location /api/ {
            limit_req zone=one burst=200;
            proxy_pass http://backend;
        }
    }
}