apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    prometheus-monitored: "true"  # Добавляем лейбл для ServiceMonitor
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http  # Это имя порта используется в ServiceMonitor!
  selector:
    app: {{ .Release.Name }}
